#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias tpon='xinput --set-prop "SynPS/2 Synaptics TouchPad" "Device Enabled" 1'
alias tpoff='xinput --set-prop "SynPS/2 Synaptics TouchPad" "Device Enabled" 0'

